# This is the configuration file for your local development environment. By
# default, it runs a single server on port 8080. To set up your server, you will
# need to add the name of the database you are connecting to and the user name.
# The password for the database is stored in the config/passwords.yaml.
#
# When running your server locally, the server ports are the same as the public
# facing ports.

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: 127.0.0.1
  publicPort: 8080
  publicScheme: http

# Configuration for the Insights server.
insightsServer:
  port: 8001
  publicHost: 127.0.0.1
  publicPort: 8001
  publicScheme: http

# Configuration for the web server.
webServer:
  port: 8000
  publicHost: 127.0.0.1
  publicPort: 8000
  publicScheme: http

# This is the database setup for your server.
database:
  host: containers-us-west-72.railway.app
  port: 6695
  name: railway
  user: postgres

# This is the setup for Redis.
redis:
  enabled: true
  host: containers-us-west-32.railway.app
  port: 7358
